export const initialValues = {
  is_gift: false,
  wants_direct_debit: false,
  is_anonymous: false,
  monthly_amount: 5,
  duration: 12,
  payer_email: '',
  payer_first_name: '',
  payer_last_name: '',
  payer_gender: 'female',
  payer_address: '',
  payer_zip_code: '',
  payer_city: '',
  payer_country: 'SI',
  giftee_email: '',
  giftee_first_name: '',
  giftee_last_name: '',
  giftee_gender: 'female',
  giftee_address: '',
  giftee_zip_code: '',
  giftee_city: '',
  giftee_country: 'SI',
};
